### ISSUE TITLE
Allow parralel file uploads

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/s3backup#5]
**Is your feature request related to a problem? Please describe.**
At the moment, s3backup uploads files 1 at a time. This is going to be quite slow, especially the first time a file tree is backed up.

**Describe the solution you'd like**
Some kind of way of configuring how many files you would like to upload at the same time

**Describe alternatives you've considered**

**Additional context**
This issue is NOT for beginners!

**Comment by dnnrly** [comment]
Consider this library for the implementatio:

https://godoc.org/golang.org/x/sync/errgroup

**Comment by ashikjm** [comment]
Hello, I would like to work on this.

I am planning to use the errgroup package as you suggested. The current UploadDifferences function will use a Group type from errgroup to spawn the goroutines and upload the file. I will also consider a way to configure the number of parallel uploads to run at any given instant.

Let me know your thoughts.

**Comment by dnnrly** [comment]
Hi, sorry for taking so long to get back to you.

Yes, this is still available. In reality it'll stay open until there's a PR that solves it. :smile:

If you raise a PR, I'll take a look and we can take it from there.

**Comment by ashikjm** [comment]
Hi, 

Thanks. I will start working on this.

**Comment by ashikjm** [comment]
@dnnrly I have raised a PR for the same. I had to do some changes to existing flow. There are no more index uploads at intervals. The index upload will happen only at the end. Please review and let me know.

Thanks :)
